CREATE TABLE "Company" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" TEXT UNIQUE,
  "description" TEXT,
  "website" TEXT UNIQUE,
  "size" TEXT,
  "location" TEXT,
  "industry" TEXT,
  "hidden" BOOLEAN DEFAULT false,
  "created_at" TIMESTAMP DEFAULT (now()) NOT NULL,
  "updated_at" TIMESTAMP DEFAULT (now()) NOT NULL,
  "intagram_url" TEXT,
  "facebook_url" TEXT,
  "twitter_url" TEXT,
  "linkedin_url" TEXT
);

CREATE TABLE "Company_Feedback" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "company_id" INTEGER,
  "author_id" INTEGER,
  "description" TEXT,
  "approved" BOOLEAN DEFAULT false,
  "created_at" TIMESTAMP DEFAULT (now()) NOT NULL,
  "updated_at" TIMESTAMP DEFAULT (now()) NOT NULL
);

CREATE TABLE "User" ( -- This is a placeholder for the user table
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL
);

ALTER TABLE "Company_Feedback" ADD FOREIGN KEY ("company_id") REFERENCES "Company" ("id");

ALTER TABLE "Company_Feedback" ADD FOREIGN KEY ("id") REFERENCES "User" ("id");

