CREATE TABLE "Company" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" VARCHAR UNIQUE,
  "description" VARCHAR,
  "website" VARCHAR UNIQUE,
  "size" VARCHAR,
  "location" VARCHAR,
  "industry" VARCHAR,
  "hidden" BOOLEAN dEFAULT false,
  "created_at" TIMESTAMP dEFAULT (now()) NOT NULL,
  "updated_at" TIMESTAMP dEFAULT (now()) NOT NULL
);

CREATE TABLE "Company_Social_Platform" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "company_id" integer,
  "url" VARCHAR,
  "typeId" VARCHAR,
  "created_at" TIMESTAMP dEFAULT (now()) NOT NULL,
  "updated_at" TIMESTAMP dEFAULT (now()) NOT NULL
);

CREATE TABLE "Social_Platform_Type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "type" VARCHAR UNIQUE,
  "created_at" TIMESTAMP dEFAULT (now()) NOT NULL,
  "updated_at" TIMESTAMP dEFAULT (now()) NOT NULL
);

CREATE TABLE "Company_Feedback" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "companyId" integer,
  "authorId" integer,
  "description" VARCHAR,
  "approved" BOOLEAN dEFAULT false,
  "created_at" TIMESTAMP dEFAULT (now()) NOT NULL,
  "updated_at" TIMESTAMP dEFAULT (now()) NOT NULL
);

CREATE TABLE "User" ( -- This is a placeholder for the user table
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL
);

ALTER TABLE "Company_Social_Platform" ADD FOREIGN KEY ("company_id") REFERENCES "Company" ("id");

ALTER TABLE "Company_Social_Platform" ADD FOREIGN KEY ("typeId") REFERENCES "Social_Platform_Type" ("id");

ALTER TABLE "Company_Feedback" ADD FOREIGN KEY ("companyId") REFERENCES "Company" ("id");

ALTER TABLE "Company_Feedback" ADD FOREIGN KEY ("id") REFERENCES "User" ("id");

