version: '3.8'
services:
  db:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: Develeb-Platform
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: