services:
  develeb-backend:
    container_name: develeb-backend
    image: develeb-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=5000

    healthcheck:
      test: curl --fail http://localhost:5000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s