openapi: 3.0.3
info:
  title: Resource API - OpenAPI 3.0
  description: This is a Recourse API based on the OpenAPI 3.0 specification.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: resource
    description: Everything about resources
  - name: resource_views
paths:
  /resources:
    get:
      tags: 
        - resource
      summary: Get list of resources
      parameters:
        - name: type
          in: query
          schema:
            type: string
          description: Filter by resource type
        - name: title
          in: query
          schema:
            type: string
          description: Filter by resource title
        - name: tags
          in: query
          schema:
            type: string
            example: community resource,news
          description: Filter by resource tags (comma separated)
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resource'
    post:
      tags:
        - resource
      summary: Create new resource
      requestBody:
        description: Create new resource
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
        required: true
      responses:
        '201':
          description: Resource created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'    
        '400':
          description: Invalid input
  /resources/{id}:
    get:
      tags:
        - resource
      summary: Get resource by id
      parameters:
        - name: id
          in: path
          description: ID of resource to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
       '200':
         description: success
         content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
       '404':
         description: resource not found
    put:
      tags:
      - resource
      summary: Update a resource
      parameters:
        - name: id
          in: path
          description: ID of resource to edit
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: updated resource
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
      responses:
        '200':
          description: Resource updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
        '404':
          description: Resource not found
    delete:
      tags:
      - resource
      summary: Delete a resource
      parameters:
        - name: id
          in: path
          description: ID of resource to delete
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Resource deleted successfully
        '404':
          description: Resource not found
    
  /resources/{id}/views:
    get:
      tags:
        - resource_views
      summary: get view count for a resource
      parameters:
        - name: id
          in: path
          description: ID of resource
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                  type: object
                  properties:
                     resource_id:
                       type: integer
                     view_count:
                       type: integer
                       example: 1000
        '404':
          description: resource not found
components:
  schemas:
    Resource:
      type: object
      required:
      - id
      - title
      - link
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          format: int64
          example: "Resource Title"
        tags:
          type: array
          items:
            type: string
          format: int32
          example: ["tag 1, tag 2"]
        description:
          type: string
          example: "description of a resource"
        link:
          type: string
          example: "https://www.resource.com"
        publish:
          type: boolean
          example: true
        type:
          type: string
          example: "community resource"
        created_at:
          type: string
          format: date
          example: "01-01-2024"
        updated_at:
          type: string
          format: date
          example: "01-01-2024"
    Resource_view:
      type: object
      required:
       - id
       - user_id
       - resource_id
       - viewed_at
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
          example: 10
        resource_id:
          type: integer
          format: int64
          example: 10
        viewed_at:
          type: string
          format: date
          example: "01-01-2024"
